//com
export const COM_SHOW_SIDE_BAR = 'COM_SHOW_SIDE_BAR' //侧边栏
export const COM_SHOW_HISTORY_LIST = 'COM_SHOW_HISTORY_LIST' //历史记录
export const COM_DELETE_HISTORY_LIST = 'COM_DELETE_HISTORY_LIST'//删除历史记录
export const COM_CLEAR_HISTORY_LIST = 'COM_CLEAR_HISTORY_LIST' //清除所有记录

export const COM_SET_PLAY_SONG = 'COM_SET_PLAY_SONG' //添加歌
