export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_TODO_ITEM = 'change_list_value'
export const DELETE_TODO_ITEM = 'del_list_value'
export const INIT_LIST_ITEM = 'init_list_action'
export const GET_INIT_LIST = 'get_init_list'
